# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Go, so we can use Go commands
      - uses: actions/setup-go@v2
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go

      # 
      - name: Build server
        run: |
          cd server
          make dev

      #
      - name: Build client
        run: |
          cd client
          make config
          make dev
          
      #
      - name: Build AI
        run: |
          cd ai
          go build
